table dimbuildingsite
	lineageTag: 20000001-0001-0001-0001-000000000001

	measure 'Site Count' = COUNTROWS(dimbuildingsite)
		displayFolder: Measures
		lineageTag: 20000001-0001-0001-0001-100000000001

	measure 'Total Contract Value GBP' = SUM(dimbuildingsite[ContractValueGBP])
		formatString: £#,0
		displayFolder: Measures
		lineageTag: 20000001-0001-0001-0001-100000000002

	column SiteId
		dataType: string
		summarizeBy: none
		sourceColumn: SiteId
		lineageTag: 20000001-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column ProjectName
		dataType: string
		summarizeBy: none
		sourceColumn: ProjectName
		lineageTag: 20000001-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		summarizeBy: none
		sourceColumn: City
		lineageTag: 20000001-0001-0001-0001-200000000003
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		summarizeBy: none
		sourceColumn: Country
		lineageTag: 20000001-0001-0001-0001-200000000004
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: string
		summarizeBy: none
		sourceColumn: StartDate
		lineageTag: 20000001-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column EndDate
		dataType: string
		summarizeBy: none
		sourceColumn: EndDate
		lineageTag: 20000001-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column ContractValueGBP
		dataType: double
		summarizeBy: sum
		sourceColumn: ContractValueGBP
		lineageTag: 20000001-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column SiteManagerId
		dataType: string
		summarizeBy: none
		sourceColumn: SiteManagerId
		lineageTag: 20000001-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		summarizeBy: none
		sourceColumn: Status
		lineageTag: 20000001-0001-0001-0001-200000000009

		annotation SummarizationSetBy = Automatic

	partition dimbuildingsite = entity
		mode: directLake
		entityName: dimbuildingsite
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
