table dimconstructionasset
	lineageTag: 20000003-0001-0001-0001-000000000001

	measure 'Asset Count' = COUNTROWS(dimconstructionasset)
		displayFolder: Measures
		lineageTag: 20000003-0001-0001-0001-100000000001

	measure 'Active Asset Count' = CALCULATE(COUNTROWS(dimconstructionasset), dimconstructionasset[Status] = "Active")
		displayFolder: Measures
		lineageTag: 20000003-0001-0001-0001-100000000002

	column AssetId
		dataType: string
		summarizeBy: none
		sourceColumn: AssetId
		lineageTag: 20000003-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column AssetName
		dataType: string
		summarizeBy: none
		sourceColumn: AssetName
		lineageTag: 20000003-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column AssetType
		dataType: string
		summarizeBy: none
		sourceColumn: AssetType
		lineageTag: 20000003-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column Manufacturer
		dataType: string
		summarizeBy: none
		sourceColumn: Manufacturer
		lineageTag: 20000003-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		summarizeBy: none
		sourceColumn: Status
		lineageTag: 20000003-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column ZoneId
		dataType: string
		summarizeBy: none
		sourceColumn: ZoneId
		lineageTag: 20000003-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	partition dimconstructionasset = entity
		mode: directLake
		entityName: dimconstructionasset
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
