table dimiotsensor
	lineageTag: 20000006-0001-0001-0001-000000000001

	measure 'Sensor Count' = COUNTROWS(dimiotsensor)
		displayFolder: Measures
		lineageTag: 20000006-0001-0001-0001-100000000001

	measure 'Active Sensor Count' = CALCULATE(COUNTROWS(dimiotsensor), dimiotsensor[Status] = "Active")
		displayFolder: Measures
		lineageTag: 20000006-0001-0001-0001-100000000002

	column SensorId
		dataType: string
		summarizeBy: none
		sourceColumn: SensorId
		lineageTag: 20000006-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column SensorName
		dataType: string
		summarizeBy: none
		sourceColumn: SensorName
		lineageTag: 20000006-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column SensorType
		dataType: string
		summarizeBy: none
		sourceColumn: SensorType
		lineageTag: 20000006-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column ZoneId
		dataType: string
		summarizeBy: none
		sourceColumn: ZoneId
		lineageTag: 20000006-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column AssetId
		dataType: string
		summarizeBy: none
		sourceColumn: AssetId
		lineageTag: 20000006-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		summarizeBy: none
		sourceColumn: Unit
		lineageTag: 20000006-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		summarizeBy: none
		sourceColumn: Status
		lineageTag: 20000006-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	partition dimiotsensor = entity
		mode: directLake
		entityName: dimiotsensor
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
