table dimworkzone
	lineageTag: 20000002-0001-0001-0001-000000000001

	measure 'Work Zone Count' = COUNTROWS(dimworkzone)
		displayFolder: Measures
		lineageTag: 20000002-0001-0001-0001-100000000001

	measure 'Avg Zone Progress %' = AVERAGE(dimworkzone[ProgressPercent])
		formatString: 0.0%
		displayFolder: Measures
		lineageTag: 20000002-0001-0001-0001-100000000002

	column ZoneId
		dataType: string
		summarizeBy: none
		sourceColumn: ZoneId
		lineageTag: 20000002-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column ZoneName
		dataType: string
		summarizeBy: none
		sourceColumn: ZoneName
		lineageTag: 20000002-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column ZoneType
		dataType: string
		summarizeBy: none
		sourceColumn: ZoneType
		lineageTag: 20000002-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column SiteId
		dataType: string
		summarizeBy: none
		sourceColumn: SiteId
		lineageTag: 20000002-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column ProgressPercent
		dataType: double
		summarizeBy: average
		sourceColumn: ProgressPercent
		lineageTag: 20000002-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: string
		summarizeBy: none
		sourceColumn: StartDate
		lineageTag: 20000002-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column PlannedEndDate
		dataType: string
		summarizeBy: none
		sourceColumn: PlannedEndDate
		lineageTag: 20000002-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	partition dimworkzone = entity
		mode: directLake
		entityName: dimworkzone
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
