table factworkprogress
	lineageTag: 20000010-0001-0001-0001-000000000001

	measure 'Avg Work Progress %' = AVERAGE(factworkprogress[ProgressPercent])
		formatString: 0.0%
		displayFolder: Measures
		lineageTag: 20000010-0001-0001-0001-100000000001

	measure 'Progress Records' = COUNTROWS(factworkprogress)
		displayFolder: Measures
		lineageTag: 20000010-0001-0001-0001-100000000002

	column ProgressId
		dataType: string
		summarizeBy: none
		sourceColumn: ProgressId
		lineageTag: 20000010-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column ZoneId
		dataType: string
		summarizeBy: none
		sourceColumn: ZoneId
		lineageTag: 20000010-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: string
		summarizeBy: none
		sourceColumn: Date
		lineageTag: 20000010-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column ProgressPercent
		dataType: double
		summarizeBy: average
		sourceColumn: ProgressPercent
		lineageTag: 20000010-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column TaskName
		dataType: string
		summarizeBy: none
		sourceColumn: TaskName
		lineageTag: 20000010-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column CompletedBy
		dataType: string
		summarizeBy: none
		sourceColumn: CompletedBy
		lineageTag: 20000010-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	partition factworkprogress = entity
		mode: directLake
		entityName: factworkprogress
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
