table factsafetyincident
	lineageTag: 20000008-0001-0001-0001-000000000001

	measure 'Incident Count' = COUNTROWS(factsafetyincident)
		displayFolder: Measures
		lineageTag: 20000008-0001-0001-0001-100000000001

	measure 'Critical Incident Count' = CALCULATE(COUNTROWS(factsafetyincident), factsafetyincident[Severity] = "Critical")
		displayFolder: Measures
		lineageTag: 20000008-0001-0001-0001-100000000002

	column IncidentId
		dataType: string
		summarizeBy: none
		sourceColumn: IncidentId
		lineageTag: 20000008-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column IncidentType
		dataType: string
		summarizeBy: none
		sourceColumn: IncidentType
		lineageTag: 20000008-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column Severity
		dataType: string
		summarizeBy: none
		sourceColumn: Severity
		lineageTag: 20000008-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column ZoneId
		dataType: string
		summarizeBy: none
		sourceColumn: ZoneId
		lineageTag: 20000008-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column WorkerId
		dataType: string
		summarizeBy: none
		sourceColumn: WorkerId
		lineageTag: 20000008-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column Timestamp
		dataType: string
		summarizeBy: none
		sourceColumn: Timestamp
		lineageTag: 20000008-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		summarizeBy: none
		sourceColumn: Status
		lineageTag: 20000008-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		summarizeBy: none
		sourceColumn: Description
		lineageTag: 20000008-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	partition factsafetyincident = entity
		mode: directLake
		entityName: factsafetyincident
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
